"""
Corrected Flexible JSON Parser - Auto-generated by Architecture Coach
Implements defensive programming, secure parsing, and flexible schema detection.
"""

import json
from typing import Dict, Any, Optional, List

class FlexibleJSONParser:
    """
    Secure and flexible JSON parser with automatic schema detection.
    Handles malformed input, missing fields, and structural variations gracefully.
    """
    
    def __init__(self):
        self.supported_schemas = [
            'metadata_body_author',  # Standard format
            'flat_title_content',    # Simple flat format  
            'nested_document',       # Deeply nested format
            'minimal_text'           # Minimal text-only format
        ]
        
    def parse(self, raw_data: str, expected_fields: Optional[List[str]] = None) -> Dict[str, Any]:
        """
        Parse JSON data with comprehensive error handling and schema flexibility.
        
        Args:
            raw_data: Raw JSON string to parse
            expected_fields: Optional list of fields caller expects
            
        Returns:
            Dict with parsed content and metadata about parsing process
        """
        result = {
            'success': False,
            'parsed_data': {},
            'detected_schema': None,
            'missing_fields': [],
            'errors': [],
            'security_validated': False
        }
        
        # Step 1: Secure JSON parsing (NO eval!)
        try:
            parsed_json = json.loads(raw_data)
            result['security_validated'] = True
        except json.JSONDecodeError as e:
            result['errors'].append(f"JSON parsing failed: {str(e)}")
            return result
        except Exception as e:
            result['errors'].append(f"Unexpected parsing error: {str(e)}")
            return result
            
        # Step 2: Schema detection and flexible parsing
        detected_schema = self._detect_schema(parsed_json)
        result['detected_schema'] = detected_schema
        
        if detected_schema:
            extracted_data = self._extract_data_by_schema(parsed_json, detected_schema)
            result['parsed_data'] = extracted_data
            result['success'] = True
            
            # Step 3: Validate expected fields (if provided)
            if expected_fields:
                missing = self._check_missing_fields(extracted_data, expected_fields)
                result['missing_fields'] = missing
                
        else:
            result['errors'].append("Could not detect compatible schema for input data")
            
        return result
    
    def _detect_schema(self, data: Dict) -> Optional[str]:
        """Detect which schema the data follows"""
        if isinstance(data, dict):
            keys = set(data.keys())
            
            # Check for standard metadata/body/author structure
            if 'metadata' in keys and isinstance(data.get('metadata'), dict):
                metadata_keys = set(data['metadata'].keys())
                if 'title' in metadata_keys:
                    return 'metadata_body_author'
                    
            # Check for flat title/content structure  
            if 'title' in keys and 'content' in keys:
                return 'flat_title_content'
                
            # Check for minimal text structure
            if len(keys) == 1 and any(isinstance(v, str) for v in data.values()):
                return 'minimal_text'
                
            # Check for nested document structure
            if 'document' in keys and isinstance(data.get('document'), dict):
                return 'nested_document'
                
        return None
        
    def _extract_data_by_schema(self, data: Dict, schema: str) -> Dict[str, Any]:
        """Extract data according to detected schema"""
        extracted = {}
        
        if schema == 'metadata_body_author':
            # Handle potential missing or malformed fields gracefully
            metadata = data.get('metadata', {})
            body = data.get('body', {})
            author = data.get('author', {})
            
            extracted.update({
                'title': self._safe_get(metadata, 'title', ''),
                'content': self._safe_get(body, 'text', str(body) if isinstance(body, str) else ''),
                'author_name': self._safe_get(author, 'name', self._safe_get(author, 'username', 'Unknown')),
                'author_email': self._safe_get(author, 'email', ''),
                'published_date': self._safe_get(metadata, 'published', '')
            })
            
        elif schema == 'flat_title_content':
            extracted.update({
                'title': data.get('title', ''),
                'content': data.get('content', ''),
                'author_name': data.get('author', 'Unknown'),
                'tags': data.get('tags', [])
            })
            
        elif schema == 'minimal_text':
            # Extract the first string value as content
            text_content = next((v for v in data.values() if isinstance(v, str)), '')
            extracted.update({
                'title': 'Untitled',
                'content': text_content,
                'author_name': 'Anonymous'
            })
            
        elif schema == 'nested_document':
            doc = data.get('document', {})
            extracted.update({
                'title': self._safe_get(doc, 'title', ''),
                'content': self._safe_get(doc, 'content', ''),
                'metadata': doc.get('metadata', {}),
                'version': doc.get('version', '1.0')
            })
            
        return extracted
        
    def _safe_get(self, obj: Dict, key: str, default: Any = None) -> Any:
        """Safely get value from dictionary with type checking"""
        if isinstance(obj, dict) and key in obj:
            return obj[key]
        return default
        
    def _check_missing_fields(self, data: Dict, expected: List[str]) -> List[str]:
        """Check for missing expected fields"""
        missing = []
        for field in expected:
            if field not in data or not data[field]:
                missing.append(field)
        return missing

# MCP-compliant interface for easy integration
def create_secure_json_parser():
    """Factory function for MCP tool registration"""
    return FlexibleJSONParser()

def parse_json_safely(raw_data: str, expected_fields: Optional[List[str]] = None) -> Dict[str, Any]:
    """Convenience function for direct usage"""
    parser = FlexibleJSONParser()
    return parser.parse(raw_data, expected_fields)

# Self-validation test suite
def run_self_validation():
    """Run comprehensive self-validation tests"""
    print("🔬 Running self-validation tests...")
    
    parser = FlexibleJSONParser()
    
    test_cases = [
        {
            'name': 'Standard metadata/body/author',
            'data': '{"metadata": {"title": "Test Article"}, "body": {"text": "Article content"}, "author": {"name": "John Doe"}}',
            'expected_success': True
        },
        {
            'name': 'Malformed body (string instead of object)',
            'data': '{"metadata": {"title": "Test"}, "body": "Not an object", "author": "Jane"}',
            'expected_success': True  # Should handle gracefully
        },
        {
            'name': 'Missing metadata structure', 
            'data': '{"title": "Simple Title", "content": "Simple content", "author": "Bob"}',
            'expected_success': True  # Should detect flat schema
        },
        {
            'name': 'Minimal text only',
            'data': '{"text": "Just some text here"}',
            'expected_success': True
        },
        {
            'name': 'Completely malformed JSON',
            'data': '{"unclosed": "bracket"',
            'expected_success': False
        }
    ]
    
    passed = 0
    total = len(test_cases)
    
    for test in test_cases:
        result = parser.parse(test['data'])
        success = result['success']
        expected = test['expected_success']
        
        if success == expected:
            print(f"✅ {test['name']}: PASSED")
            passed += 1
        else:
            print(f"❌ {test['name']}: FAILED (expected {expected}, got {success})")
            print(f"   Error: {result.get('errors', [])}")
            
    print(f"\n📊 Self-validation results: {passed}/{total} tests passed")
    
    if passed == total:
        print("🎉 All tests passed! Parser is ready for production.")
        return True
    else:
        print("⚠️  Some tests failed. Parser needs further correction.")
        return False

if __name__ == "__main__":
    success = run_self_validation()
    if success:
        print("\n✅ Recursive self-correction completed successfully!")
        print("The corrected parser is now secure, flexible, and production-ready.")