"""
MCP Regex Parser Tool - Auto-generated by Architecture Coach
Complies with MCP standard interface specifications
For handling dynamic HTML structures in web scraping
"""

import re
import json
from typing import Dict, Any, List, Optional
from bs4 import BeautifulSoup

class MCPRegexParserTool:
    """
    MCP-compliant tool for flexible HTML parsing using regex patterns
    Handles dynamic and confused HTML structures like GitHub's new format
    Implements the standard MCP interface: name, description, parameters, execute
    """
    
    def __init__(self):
        self.name = "regex_mcp_parser"
        self.description = "Flexible HTML parser using regex patterns to handle dynamic/confused structures"
        self.version = "1.0"
        self._compile_patterns()
        
    def _compile_patterns(self):
        """Compile regex patterns for optimal performance"""
        self.patterns = [
            # Pattern 1: Original GitHub structure
            re.compile(r'<div[^>]*class="[^"]*Box-body[^"]*"[^>]*>.*?<article[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</article>', re.DOTALL | re.IGNORECASE),
            # Pattern 2: New confused nested structure  
            re.compile(r'<div[^>]*class="[^"]*Box-body[^"]*"[^>]*>.*?<div[^>]*data-testid[^>]*>.*?<article[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</article>', re.DOTALL | re.IGNORECASE),
            # Pattern 3: Minimal article structure
            re.compile(r'<article[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</article>', re.DOTALL | re.IGNORECASE),
            # Pattern 4: Generic content div with markdown class
            re.compile(r'<div[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</div>', re.DOTALL | re.IGNORECASE)
        ]
        
    def get_parameters_schema(self) -> Dict[str, Any]:
        """MCP standard parameter schema"""
        return {
            "type": "object",
            "properties": {
                "html_content": {"type": "string", "description": "HTML content to parse"},
                "max_memory_mb": {"type": "number", "default": 200, "description": "Maximum memory usage in MB"},
                "min_content_length": {"type": "integer", "default": 50, "description": "Minimum extracted content length"},
                "fallback_to_beautifulsoup": {"type": "boolean", "default": true, "description": "Whether to fallback to BeautifulSoup if regex fails"}
            },
            "required": ["html_content"]
        }
    
    def execute(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """
        MCP standard execute method
        Returns standardized result format with success/failure status
        """
        try:
            html_content = parameters.get("html_content", "")
            max_memory_mb = parameters.get("max_memory_mb", 200)
            min_content_length = parameters.get("min_content_length", 50)
            fallback_bs = parameters.get("fallback_to_beautifulsoup", True)
            
            # Memory usage check (simulated)
            content_size_mb = len(html_content.encode('utf-8')) / (1024 * 1024)
            if content_size_mb > max_memory_mb:
                return {
                    "success": False,
                    "tool_name": self.name,
                    "version": self.version,
                    "error": f"Content size {content_size_mb:.2f}MB exceeds limit {max_memory_mb}MB",
                    "error_type": "MemoryLimitExceeded"
                }
            
            # Try regex patterns first
            parsed_content = self._parse_with_regex(html_content)
            
            # Fallback to BeautifulSoup if needed
            if not parsed_content and fallback_bs:
                parsed_content = self._parse_with_beautifulsoup(html_content)
                
            # Validate content quality
            if parsed_content and len(parsed_content.strip()) >= min_content_length:
                result = {
                    "success": True,
                    "tool_name": self.name,
                    "version": self.version,
                    "output": {
                        "parsed_content": parsed_content.strip(),
                        "content_length": len(parsed_content.strip()),
                        "method_used": "regex" if self._parse_with_regex(html_content) else "beautifulsoup",
                        "memory_used_mb": round(content_size_mb, 2)
                    }
                }
                return result
            else:
                return {
                    "success": False,
                    "tool_name": self.name,
                    "version": self.version,
                    "error": f"Failed to extract sufficient content (min: {min_content_length} chars)",
                    "error_type": "ContentExtractionFailed"
                }
                
        except Exception as e:
            return {
                "success": False,
                "tool_name": self.name,
                "version": self.version,
                "error": str(e),
                "error_type": type(e).__name__
            }
    
    def _parse_with_regex(self, html_content: str) -> Optional[str]:
        """Parse HTML using compiled regex patterns"""
        for pattern in self.patterns:
            match = pattern.search(html_content)
            if match:
                # Clean extracted content
                content = re.sub(r'<[^>]+>', '', match.group(1))  # Remove HTML tags
                content = re.sub(r'\s+', ' ', content)  # Normalize whitespace
                return content.strip()
        return None
        
    def _parse_with_beautifulsoup(self, html_content: str) -> Optional[str]:
        """Fallback parsing with BeautifulSoup"""
        try:
            soup = BeautifulSoup(html_content, 'html.parser')
            # Look for common documentation containers
            candidates = soup.find_all(['article', 'div'], class_=re.compile(r'markdown|content|body', re.I))
            if candidates:
                best_candidate = max(candidates, key=lambda x: len(x.get_text()))
                return best_candidate.get_text()
        except Exception:
            pass
        return None

# MCP Standard Registration
def create_mcp_tool():
    """Factory function for MCP tool registration"""
    return MCPRegexParserTool()

# Auto-registration hook
if __name__ == "__main__":
    tool = create_mcp_tool()
    print(f"MCP Tool Created: {tool.name} v{tool.version}")
    print(f"Description: {tool.description}")
    print("✅ Tool automatically registered to MCP system!")