"""
Shadow Sandbox: 3 Parser Solutions for GitHub HTML Structure Evolution
Generated by Architecture Coach for Memory Evolution Validation
"""

import re
import json
from typing import Dict, Any, List
from bs4 import BeautifulSoup

class ParserSolutionBase:
    """Base class for parser solutions with standardized evaluation interface"""
    
    def __init__(self, name: str):
        self.name = name
        self.memory_usage_mb = 0
        self.parse_success_rate = 0.0
        self.architecture_coupling = 0.0  # 0 = fully decoupled, 1 = tightly coupled
        
    def parse(self, html_content: str) -> Dict[str, Any]:
        """Parse HTML content - to be implemented by subclasses"""
        raise NotImplementedError
        
    def evaluate(self, test_cases: List[Dict]) -> Dict[str, Any]:
        """Evaluate solution against test cases"""
        successes = 0
        total_memory = 0
        
        for test_case in test_cases:
            try:
                result = self.parse(test_case['html'])
                if result and 'content' in result:
                    successes += 1
                # Simulate memory usage tracking
                total_memory += len(test_case['html']) / (1024 * 1024)  # MB
            except Exception:
                pass
                
        self.parse_success_rate = successes / len(test_cases) if test_cases else 0
        self.memory_usage_mb = total_memory / len(test_cases) if test_cases else 0
        
        # Architecture coupling assessment (lower is better)
        self.architecture_coupling = self._assess_coupling()
        
        return {
            'name': self.name,
            'parse_success_rate': self.parse_success_rate,
            'memory_usage_mb': self.memory_usage_mb,
            'architecture_coupling': self.architecture_coupling,
            'reward_score': self._calculate_reward_score()
        }
    
    def _assess_coupling(self) -> float:
        """Assess architectural coupling (implementation specific)"""
        raise NotImplementedError
        
    def _calculate_reward_score(self) -> float:
        """Calculate multi-dimensional reward score"""
        # Weighted scoring: success rate (50%), memory (25%), coupling (25%)
        success_weight = min(self.parse_success_rate * 2.0, 1.0)  # Normalize to 0-1
        memory_weight = max(0, 1.0 - (self.memory_usage_mb / 200.0))  # ≤200MB = full score
        coupling_weight = 1.0 - self.architecture_coupling  # Lower coupling = higher score
        
        reward = (success_weight * 0.5 + memory_weight * 0.25 + coupling_weight * 0.25) * 10
        return round(reward, 2)

class Solution1_CSSSelectorFlexible(ParserSolutionBase):
    """Solution 1: Enhanced CSS Selector with Multiple Fallback Paths"""
    
    def __init__(self):
        super().__init__("CSS_Selector_Flexible")
        
    def parse(self, html_content: str) -> Dict[str, Any]:
        soup = BeautifulSoup(html_content, 'html.parser')
        
        # Multiple fallback paths for different GitHub structures
        selectors = [
            'div.Box-body article.markdown-body',
            'div.Box-body div[data-testid] article.markdown-body', 
            'div.Box-body .markdown-body article',
            'article.markdown-body'
        ]
        
        for selector in selectors:
            try:
                element = soup.select_one(selector)
                if element:
                    return {'content': element.get_text(), 'selector_used': selector}
            except Exception:
                continue
                
        return None
        
    def _assess_coupling(self) -> float:
        return 0.3  # Medium coupling - depends on specific CSS patterns

class Solution2_RegexPatternMatching(ParserSolutionBase):
    """Solution 2: Regex-based Pattern Matching for Dynamic Structures"""
    
    def __init__(self):
        super().__init__("Regex_Pattern_Matching")
        
    def parse(self, html_content: str) -> Dict[str, Any]:
        # Flexible regex patterns that match various GitHub structures
        patterns = [
            r'<div[^>]*class="[^"]*Box-body[^"]*"[^>]*>.*?<article[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</article>',
            r'<div[^>]*class="[^"]*Box-body[^"]*"[^>]*>.*?<div[^>]*data-testid[^>]*>.*?<article[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</article>',
            r'<article[^>]*class="[^"]*markdown-body[^"]*"[^>]*>(.*?)</article>'
        ]
        
        for pattern in patterns:
            match = re.search(pattern, html_content, re.DOTALL | re.IGNORECASE)
            if match:
                # Clean the extracted content
                content = re.sub(r'<[^>]+>', '', match.group(1))  # Remove HTML tags
                return {'content': content.strip(), 'pattern_used': pattern}
                
        return None
        
    def _assess_coupling(self) -> float:
        return 0.1  # Low coupling - regex patterns are flexible

class Solution3_ContentSemanticAnalysis(ParserSolutionBase):
    """Solution 3: Semantic Content Analysis with ML-like Heuristics"""
    
    def __init__(self):
        super().__init__("Content_Semantic_Analysis")
        
    def parse(self, html_content: str) -> Dict[str, Any]:
        soup = BeautifulSoup(html_content, 'html.parser')
        
        # Find elements that contain documentation-like content
        candidates = []
        
        # Look for elements with common documentation indicators
        for element in soup.find_all(['div', 'article', 'section']):
            text = element.get_text()
            if len(text) > 100:  # Minimum content length
                # Score based on documentation-like characteristics
                score = 0
                if 'class' in element.attrs:
                    classes = ' '.join(element['class']).lower()
                    if 'markdown' in classes or 'content' in classes or 'body' in classes:
                        score += 2
                if element.name == 'article':
                    score += 1
                if len(text.split()) > 20:  # Substantial content
                    score += 1
                    
                if score >= 2:
                    candidates.append((score, element))
                    
        if candidates:
            # Return highest scoring candidate
            best_candidate = max(candidates, key=lambda x: x[0])
            return {'content': best_candidate[1].get_text(), 'score': best_candidate[0]}
            
        return None
        
    def _assess_coupling(self) -> float:
        return 0.2  # Low-medium coupling - semantic approach is flexible

def generate_test_cases():
    """Generate test cases simulating different GitHub HTML structures"""
    return [
        {
            'name': 'Original_GitHub_Structure',
            'html': '''
            <div class="Box-body article-content" itemprop="articleBody">
                <article class="markdown-body entry-content container-lg">
                    Original GitHub documentation content here.
                </article>
            </div>
            ''',
            'expected_content_length': 50
        },
        {
            'name': 'New_Confused_Structure', 
            'html': '''
            <div class="Box-body article-content" itemprop="articleBody">
                <div data-testid="confused-nested-wrapper">
                    <div class="markdown-body">
                        <article class="markdown-body entry-content container-lg">
                            New confused GitHub documentation with dynamic wrappers.
                        </article>
                    </div>
                </div>
            </div>
            ''',
            'expected_content_length': 70
        },
        {
            'name': 'Minimal_Structure',
            'html': '''
            <article class="markdown-body">
                Minimal documentation structure.
            </article>
            ''',
            'expected_content_length': 35
        }
    ]

def run_shadow_sandbox_evaluation():
    """Run comprehensive evaluation of all three solutions"""
    print("🔬 Running Shadow Sandbox Evaluation...")
    
    test_cases = generate_test_cases()
    solutions = [
        Solution1_CSSSelectorFlexible(),
        Solution2_RegexPatternMatching(), 
        Solution3_ContentSemanticAnalysis()
    ]
    
    results = []
    for solution in solutions:
        print(f"\nEvaluating {solution.name}...")
        result = solution.evaluate(test_cases)
        results.append(result)
        print(f"  Success Rate: {result['parse_success_rate']:.2%}")
        print(f"  Memory Usage: {result['memory_usage_mb']:.2f} MB")
        print(f"  Architecture Coupling: {result['architecture_coupling']:.2f}")
        print(f"  Reward Score: {result['reward_score']:.2f}/10")
        
    # Determine winner
    winner = max(results, key=lambda x: x['reward_score'])
    print(f"\n🏆 Winner: {winner['name']} (Reward: {winner['reward_score']}/10)")
    
    return {
        'all_results': results,
        'winner': winner,
        'test_cases_count': len(test_cases)
    }

if __name__ == "__main__":
    evaluation_results = run_shadow_sandbox_evaluation()
    
    # Save results for architecture coach review
    with open('/Users/zhaoqinhuang/david_project/shadow_sandbox_evaluation_report.json', 'w') as f:
        json.dump(evaluation_results, f, indent=2)
        
    print("\n✅ Shadow Sandbox Evaluation Complete!")
    print("Results saved to shadow_sandbox_evaluation_report.json")